apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AndyNg195/devops-prj3.git
    targetRevision: main
    path: child-apps                       # path that contains ONLY child-apps
    directory:
      recurse: true                        # pick up every *.yaml beneath
  destination:                             # root app creates no resources itself
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { selfHeal: true, prune: true }
