apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-staging
  namespace: argocd
  annotations:
    # Danh sách hình ảnh, có thể dùng cùng cấu hình với app-dev hoặc tùy chỉnh nếu muốn
    argocd-image-updater.argoproj.io/image-list: config-server=andyng195/spring-petclinic-config-server,discovery-server=andyng195/spring-petclinic-discovery-server,admin-server=andyng195/spring-petclinic-admin-server,customers-service=andyng195/spring-petclinic-customers-service,visits-service=andyng195/spring-petclinic-visits-service,vets-service=andyng195/spring-petclinic-vets-service,api-gateway=andyng195/spring-petclinic-api-gateway

    argocd-image-updater.argoproj.io/api-gateway.helm.image-name: spring-petclinic-api-gateway
    argocd-image-updater.argoproj.io/api-gateway.helm.image-tag: services.api-gateway.image.tag

    argocd-image-updater.argoproj.io/config-server.helm.image-name: spring-petclinic-config-server
    argocd-image-updater.argoproj.io/config-server.helm.image-tag: services.config-server.image.tag

    argocd-image-updater.argoproj.io/discovery-server.helm.image-name: spring-petclinic-discovery-server
    argocd-image-updater.argoproj.io/discovery-server.helm.image-tag: services.discovery-server.image.tag

    argocd-image-updater.argoproj.io/admin-server.helm.image-name: spring-petclinic-admin-server
    argocd-image-updater.argoproj.io/admin-server.helm.image-tag: services.admin-server.image.tag

    argocd-image-updater.argoproj.io/customers-service.helm.image-name: spring-petclinic-customers-service
    argocd-image-updater.argoproj.io/customers-service.helm.image-tag: services.customers-service.image.tag

    argocd-image-updater.argoproj.io/visits-service.helm.image-name: spring-petclinic-visits-service
    argocd-image-updater.argoproj.io/visits-service.helm.image-tag: services.visits-service.image.tag

    argocd-image-updater.argoproj.io/vets-service.helm.image-name: spring-petclinic-vets-service
    argocd-image-updater.argoproj.io/vets-service.helm.image-tag: services.vets-service.image.tag

    # Cho phép ghi ngược về Git (ví dụ vào values.yaml)
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/AndyNg195/argocd-devops.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml                   
        - environments/values.staging.yaml 

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true