global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # ------ DEV ------- 
  - job_name: api-gateway-dev
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway.dev.svc.cluster.local:8080']

  - job_name: customers-service-dev
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['customers-service.dev.svc.cluster.local:8081']

  - job_name: visits-service-dev
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['visits-service.dev.svc.cluster.local:8082']

  - job_name: vets-service-dev
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['vets-service.dev.svc.cluster.local:8083']

  # ------ STAGING ------- 
  - job_name: api-gateway-staging
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway.staging.svc.cluster.local:8080']

  - job_name: customers-service-staging
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['customers-service.staging.svc.cluster.local:8081']

  - job_name: visits-service-staging
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['visits-service.staging.svc.cluster.local:8082']

  - job_name: vets-service-staging
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['vets-service.staging.svc.cluster.local:8083']
