apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      releaseName: loki
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage_config:
            filesystem:
              directory: /tmp/loki/chunks
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          ruler:
            enable_api: true
          auth_enabled: false

        pattern_ingester:
          enabled: true
          stages:
            - regex:
                expression: '.*\[(?P<trace_id>[0-9a-f]{16,32})-(?P<span_id>[0-9a-f]{16,32})\].*'
            - labels:
                trace_id: "{{ .trace_id }}"
                span_id: "{{ .span_id }}"

        minio:
          enabled: false
              
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1
          persistence:
            storageClass: local-path
            accessModes:
              - ReadWriteOnce
            size: 5Gi
          resources:
            requests:
              cpu: "300m"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "4Gi"

        sidecar:
          image:
            repository: kiwigrid/k8s-sidecar
            tag: 1.30.0
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi

        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        chunksCache:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        resultsCache:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: loki

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
